### ISSUE TITLE
The pagination system is tied to the Search annotation class

### ISSUE THREAD

**Issue by juchi** [open-orchestra/open-orchestra-libs#12]
The FilterTrait::generateFilterSort() method expects the $dsecriptionEntity to be an array object implementing the "getField()" method. I practice this means that orchestra expects an array of Search annotation objects. Orchestra should provide an interface for the objects to push into the description array so we are not tied to the annotation system.

**Comment by alavieille** [comment]
it's fix in this PR https://github.com/open-orchestra/open-orchestra-libs/pull/23
and documation about this update in https://github.com/open-orchestra/open-orchestra-docs/pull/94#issuecomment-141094277
